site_name: 我的文档
site_description: 使用 MkDocs 构建的文档站点
site_url: https://seaflynn.github.io/doc-collect/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - footnotes
  - toc:
      permalink: true

nav:
  - 首页: index.md
  - 文档写作:
    - Markdown 入门到入土: tag_markdown用法/markdown入门到入土.md
  - 前端:
    - 错误记录:
      - TailwindCSS错误记录: 前端/错误记录/err-tailwindcss.md
  - 关于AI:
    - b站:
      - 周鸿祎-AI创业-百大AI应用系列视频博客: 关于AI/b站/周鸿祎-ai创业-百大AI应用系列视频博客.md
  - 杂项:
    - 本地构建docsify: 杂项/本地构建docsify.md
    - 本地构建mkdocs: 杂项/本地构建mkdocs.md
    - vscode插件: 杂项/vscode-插件.md
    - Oh-My-Posh安装: 杂项/Oh-My-Posh安装.md
    - win终端插件安装: 杂项/win-类fish.md
  - cpp:
    - cpo: cpp/cpo.md
  - QT:
    - qml笔记: QT/qml笔记.md
    - 笔记: QT/笔记.md
    - qml-background-contentitem-分离: QT/qml-background-contentitem-分离.md
    - qt-qml常用组件: QT/qt-qml常用组件.md
